import{a as h,i as p,S as b}from"./assets/vendor-951421c8.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function c(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=c(e);fetch(e.href,t)}})();const L=document.querySelector(".form"),l=document.querySelector(".gallery"),w=document.querySelector("div"),S=document.querySelector("input"),d=document.querySelector(".load-more");let u="",i=1;const m=()=>{const o=document.createElement("span");o.classList.add("loader"),w.append(o)},y=()=>{const o=document.querySelector(".loader");o&&o.remove()},v=()=>{d.style.display="block"},$=()=>{d.style.display="none"};L.addEventListener("submit",async o=>{o.preventDefault(),m(),l.innerHTML="",u=S.value,i=1;try{await f(),v()}catch(s){console.log(s)}finally{y()}});d.addEventListener("click",async()=>{m();try{i++,await f()}catch(o){console.log(o)}finally{y()}});async function f(){const c=`https://pixabay.com/api/?key=42288638-d7f8a30b0a31b090439479823&q=${u}&image_type=photo&orientation=horizontal&safesearch=true&page=${i}&per_page=${15}`;try{const r=await h.get(c);if(r.data.hits.length===0)p.error({message:"Sorry, there are no images matching <br>your search query. Please try again!</br>",position:"center",transitionIn:"fadeInLeft"});else{const e=r.data.totalHits;i*15>=e&&($(),p.info({message:"We're sorry, but you've reached the end of search results.",position:"center",transitionIn:"fadeInLeft"}));const a=l.querySelector(".gallery-item").getBoundingClientRect().height,g=r.data.hits.map(n=>`
          <li class="gallery-item">
            <a href="${n.largeImageURL}">
              <img class="gallery-image" src="${n.webformatURL}" alt="${n.tags}">
            </a>
            <p><b>Likes: </b>${n.likes}</p>
            <p><b>Views: </b>${n.views}</p>
            <p><b>Comments: </b>${n.comments}</p>
            <p><b>Downloads: </b>${n.downloads}</p>
          </li>`).join("");l.insertAdjacentHTML("beforeend",g),new b(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",fadeSpeed:150,captionSelector:"img",captionDelay:250}).on("show.simplelightbox").refresh(),window.scrollBy({top:a*2,behavior:"smooth"})}}catch(r){throw new Error(r.response.status)}}
//# sourceMappingURL=commonHelpers.js.map
