import{i as l,a as L,S as w}from"./assets/vendor-951421c8.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function d(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=d(e);fetch(e.href,t)}})();const S=document.querySelector(".form"),c=document.querySelector(".gallery"),f=document.querySelector("div"),v=document.querySelector("input"),n=document.createElement("button");n.textContent="Load more";n.classList.add("load-more-btn");f.append(n);let m=1,g="",p=0,u=0;const y=()=>{const r=document.createElement("span");r.classList.add("loader"),f.insertBefore(r,n)},h=()=>{const r=document.querySelector(".loader");r&&r.remove()},I=()=>{n.style.display="block"},$=()=>{n.style.display="none"};S.addEventListener("submit",async r=>{r.preventDefault(),g=v.value,y(),m=1,c.innerHTML="";try{await b()}catch(a){console.error(a),l.error({message:"An error occurred while fetching images. Please try again later.",position:"center",transitionIn:"fadeInLeft"})}h()});n.addEventListener("click",async()=>{m++,y();try{await b()}catch(r){console.error(r),l.error({message:"An error occurred while fetching images. Please try again later.",position:"center",transitionIn:"fadeInLeft"})}h()});async function b(){const d=`https://pixabay.com/api/?key=42288638-d7f8a30b0a31b090439479823&q=${g}&image_type=photo&orientation=horizontal&safesearch=true&page=${m}&per_page=${15}`;try{const e=(await L.get(d)).data;if(p=e.totalHits,e.hits.length===0)l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"center",transitionIn:"fadeInLeft"});else{const t=e.hits.map(o=>`
          <li class="gallery-item"><a href="${o.largeImageURL}">
          <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}"></a>
          <p><b>Likes: </b>${o.likes}</p>
          <p><b>Views: </b>${o.views}</p>
          <p><b>Comments: </b>${o.comments}</p>
          <p><b>Downloads: </b>${o.downloads}</p>
          </li>`).join("");c.insertAdjacentHTML("beforeend",t),new w(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",fadeSpeed:150,captionSelector:"img",captionDelay:250}).on("show.simplelightbox").refresh(),I(),c.querySelectorAll(".gallery-item").length>=p&&($(),l.info({message:"We're sorry, but you've reached the end of search results.",position:"center",transitionIn:"fadeInLeft"})),u===0&&(u=c.querySelector(".gallery-item").getBoundingClientRect().height),window.scrollBy({top:u*2,behavior:"smooth"})}}catch(s){throw new Error(s.message)}}
//# sourceMappingURL=commonHelpers.js.map
